export const groupOptionsMap: Record<string, { label: string; value: string }[]> = {
    "26": [
        { label: "Bagerhat Sadar", value: "184" },
        { label: "Chitalmari", value: "185" },
        { label: "Fakirhat", value: "186" },
        { label: "Kachua", value: "187" },
        { label: "Mollahat", value: "188" },
        { label: "Mongla", value: "189" },
        { label: "Morrelganj", value: "190" },
        { label: "Rampal", value: "191" },
        { label: "Sarankhola", value: "192" },
    ],
    "64": [
        { label: "Alikadam", value: "547" },
        { label: "Bandarban Sadar", value: "548" },
        { label: "Lama", value: "549" },
        { label: "Naikhongchhari", value: "550" },
        { label: "Rowangchhari", value: "551" },
        { label: "Ruma", value: "552" },
        { label: "Thanchi", value: "553" },
    ],
    "32": [
        { label: "Amtali", value: "228" },
        { label: "Bamna", value: "229" },
        { label: "Barguna Sadar", value: "230" },
        { label: "Betagi", value: "231" },
        { label: "Patharghata", value: "232" },
        { label: "TalToli", value: "567" },
    ],
    "29": [
        { label: "Agailihara", value: "204" },
        { label: "Babuganj", value: "205" },
        { label: "Bakerganj", value: "206" },
        { label: "Banari Para", value: "207" },
        { label: "Barishal Sadar (Kotwali)", value: "208" },
        { label: "Gaurnadi", value: "209" },
        { label: "Hizla", value: "210" },
        { label: "Mehendiganj", value: "211" },
        { label: "Muladi", value: "212" },
        { label: "Wazirpur", value: "213" },
    ],
    "30": [
        { label: "Bhola Sadar", value: "214" },
        { label: "Burhanuddin", value: "215" },
        { label: "Char Fasson", value: "216" },
        { label: "Daulatkhan", value: "217" },
        { label: "Lalmohan", value: "218" },
        { label: "Manpura", value: "219" },
        { label: "Tazumuddin", value: "220" },
    ],
    "10": [
        { label: "Adamdighi", value: "65" },
        { label: "Bogura Sadar", value: "66" },
        { label: "Dhunat", value: "67" },
        { label: "Dhupchanchia", value: "68" },
        { label: "Gabtali", value: "69" },
        { label: "Kahaloo", value: "70" },
        { label: "Nandigram", value: "71" },
        { label: "Sariakandi", value: "72" },
        { label: "Shajhanpur", value: "73" },
        { label: "Sherpur", value: "74" },
        { label: "Shibganj", value: "75" },
        { label: "Sonatola", value: "76" },
    ],
    "54": [
        { label: "Akhaura", value: "444" },
        { label: "Ashuganj", value: "445" },
        { label: "Banchharampur", value: "446" },
        { label: "Bijoynagar", value: "565" },
        { label: "Brahmanbaria Sadar", value: "447" },
        { label: "Kasba", value: "448" },
        { label: "Nabinagar", value: "449" },
        { label: "Nasirnagar", value: "450" },
        { label: "Sarail", value: "451" },
    ],
    "56": [
        { label: "Chandpur Sadar", value: "468" },
        { label: "Faridganj", value: "469" },
        { label: "Haim Char", value: "470" },
        { label: "Hajiganj", value: "471" },
        { label: "Kachua", value: "472" },
        { label: "Matlab", value: "473" },
        { label: "Shahrasti", value: "474" },
        { label: "Uttar Matlab", value: "475" },
    ],
    "13": [
        { label: "Bholahat", value: "94" },
        { label: "Gomastapur", value: "95" },
        { label: "Nachole", value: "96" },
        { label: "Nawabganj Sadar", value: "97" },
        { label: "Shibganj", value: "98" },
    ],
    "60": [
        { label: "Akbar Shah", value: "561" },
        { label: "Anowara", value: "496" },
        { label: "Bakalia", value: "497" },
        { label: "Bandar(Chitt. Port)", value: "498" },
        { label: "Banshkhali", value: "499" },
        { label: "Bayejid Bostami", value: "500" },
        { label: "Boalkhali", value: "501" },
        { label: "Chandanish", value: "502" },
        { label: "Chandgaon", value: "503" },
        { label: "Chawkbazar", value: "562" },
        { label: "Double Mooring", value: "504" },
        { label: "EPZ", value: "564" },
        { label: "Fatikchhari", value: "505" },
        { label: "Halishahar", value: "506" },
        { label: "Hathazari", value: "507" },
        { label: "Karnafuli", value: "508" },
        { label: "Khulshi", value: "509" },
        { label: "Kotwali", value: "510" },
        { label: "Lohagara", value: "511" },
        { label: "Mirsharai", value: "512" },
        { label: "Pahartali", value: "513" },
        { label: "Panchlaish", value: "514" },
        { label: "Patenga", value: "560" },
        { label: "Patiya", value: "515" },
        { label: "Rangunia", value: "516" },
        { label: "Raozan", value: "517" },
        { label: "Sadarghat", value: "563" },
        { label: "Sandwip", value: "518" },
        { label: "Satkania", value: "519" },
        { label: "Sitakunda", value: "520" },
    ],
    "19": [
        { label: "Alamdanga", value: "138" },
        { label: "Chuadanga Sadar", value: "139" },
        { label: "Damurhuda", value: "140" },
        { label: "Jiban Nagar", value: "141" },
    ],
    "61": [
        { label: "Chakaria", value: "521" },
        { label: "Cox`s Bazar Sadar", value: "522" },
        { label: "Kutubdia", value: "523" },
        { label: "Maheshkhali", value: "524" },
        { label: "Pekua", value: "525" },
        { label: "Ramu", value: "526" },
        { label: "Teknaf", value: "527" },
        { label: "Ukhia", value: "528" },
    ],
    "55": [
        { label: "Barura", value: "452" },
        { label: "Brahaman Para", value: "453" },
        { label: "Burichang", value: "454" },
        { label: "Chandina", value: "455" },
        { label: "Chauddagram", value: "456" },
        { label: "Cumilla Sadar", value: "457" },
        { label: "Cumilla Sadar South", value: "458" },
        { label: "Daudkandi", value: "459" },
        { label: "Debidwar", value: "460" },
        { label: "Homna", value: "461" },
        { label: "Laksam", value: "462" },
        { label: "Lalmai", value: "566" },
        { label: "Meghna", value: "464" },
        { label: "Monohorganj", value: "465" },
        { label: "Muradnagar", value: "466" },
        { label: "Nangalkot", value: "463" },
        { label: "Titas", value: "467" },
    ],
    "40": [
        { label: "Adabor", value: "299" },
        { label: "Airport", value: "300" },
        { label: "Badda", value: "301" },
        { label: "Banani", value: "302" },
        { label: "Bangshal", value: "303" },
        { label: "Bhashantek", value: "304" },
        { label: "Cantonment", value: "305" },
        { label: "Chackbazar", value: "306" },
        { label: "Dakshin Khan", value: "307" },
        { label: "Darus-Salam", value: "308" },
        { label: "Demra", value: "309" },
        { label: "Dhamrai", value: "310" },
        { label: "Dhanmondi", value: "311" },
        { label: "Dohar", value: "312" },
        { label: "Gandaria", value: "313" },
        { label: "Gulshan", value: "314" },
        { label: "Hatirjheel", value: "315" },
        { label: "Hazaribhag", value: "316" },
        { label: "Jattrabari", value: "317" },
        { label: "Kadamtoli", value: "318" },
        { label: "Kafrul", value: "319" },
        { label: "Kalabagan", value: "320" },
        { label: "Kamrangir Char", value: "321" },
        { label: "Keraniganj Model", value: "322" },
        { label: "Khilgaon", value: "323" },
        { label: "Khilkhet", value: "324" },
        { label: "Kotwali", value: "325" },
        { label: "Lalbag", value: "326" },
        { label: "Mirpur Model", value: "327" },
        { label: "Mohammadpur", value: "328" },
        { label: "Motijheel", value: "329" },
        { label: "Mugda", value: "330" },
        { label: "New Market", value: "331" },
        { label: "Nawabganj", value: "332" },
        { label: "Pallabi", value: "333" },
        { label: "Paltan Model", value: "334" },
        { label: "Ramna Model", value: "335" },
        { label: "Rampura", value: "336" },
        { label: "Rupnagar", value: "337" },
        { label: "Sabujbhag", value: "338" },
        { label: "Shah Ali", value: "339" },
        { label: "Shahbag", value: "340" },
        { label: "Savar", value: "341" },
        { label: "Shahjahanpur", value: "342" },
        { label: "Sher e Bangla Nagar", value: "343" },
        { label: "Shyampur", value: "344" },
        { label: "South Keraniganj", value: "558" },
        { label: "Sutrapur", value: "345" },
        { label: "Tejgaon", value: "346" },
        { label: "Tejgaon Industrial", value: "347" },
        { label: "Turag", value: "348" },
        { label: "Uttar Khan", value: "349" },
        { label: "Uttara East", value: "350" },
        { label: "Uttara West", value: "351" },
        { label: "Vatara", value: "352" },
        { label: "Wari", value: "353" },
    ],
    "3": [
        { label: "Biral", value: "11" },
        { label: "Birampur", value: "12" },
        { label: "Birganj", value: "13" },
        { label: "Bochaganj", value: "14" },
        { label: "Chirirbandar", value: "15" },
        { label: "Dinajpur Sadar", value: "16" },
        { label: "Fulbari", value: "17" },
        { label: "Ghoraghat", value: "18" },
        { label: "Hakimpur", value: "19" },
        { label: "Kaharole", value: "20" },
        { label: "Khansama", value: "21" },
        { label: "Nawabganj", value: "22" },
        { label: "Parbatipur", value: "23" },
    ],
    "45": [
        { label: "Alfadanga", value: "377" },
        { label: "Bhanga", value: "378" },
        { label: "Boalmari", value: "379" },
        { label: "Char Bhadrasan", value: "380" },
        { label: "Faridpur Sadar", value: "381" },
        { label: "Madukhali", value: "382" },
        { label: "Nagarkanda", value: "383" },
        { label: "Sadarpur", value: "384" },
        { label: "Saltha", value: "385" },
    ],
    "59": [
        { label: "Chhagalnayian", value: "490" },
        { label: "Daganbhuyian", value: "491" },
        { label: "Feni Sadar", value: "492" },
        { label: "Fulgazi", value: "493" },
        { label: "Parshuram", value: "494" },
        { label: "Sonagazi", value: "495" },
    ],
    "8": [
        { label: "Fulchhari", value: "53" },
        { label: "Gaibanda Sadar", value: "54" },
        { label: "Gobidaganj", value: "55" },
        { label: "Palashbari", value: "56" },
        { label: "Sadullapur", value: "57" },
        { label: "Saghatta", value: "58" },
        { label: "Sundarganj", value: "59" },
    ],
    "41": [
        { label: "Gazipur Sadar", value: "354" },
        { label: "Kaliakair", value: "355" },
        { label: "Kaliganj", value: "356" },
        { label: "Kapasia", value: "357" },
        { label: "Sreepur", value: "358" },
        { label: "Tongi", value: "359" },
    ],
    "47": [
        { label: "Gopalganj Sadar", value: "391" },
        { label: "Kashiani", value: "392" },
        { label: "Kotalipara", value: "393" },
        { label: "Muksudpur", value: "394" },
        { label: "Tungi Para", value: "395" },
    ],
    "53": [
        { label: "Ajmiriganj", value: "436" },
        { label: "Bahubal", value: "437" },
        { label: "Baniachung", value: "438" },
        { label: "Chunarughat", value: "439" },
        { label: "Habiganj Sadar", value: "440" },
        { label: "Lakhai", value: "441" },
        { label: "Madhabpur", value: "442" },
        { label: "Nabiganj", value: "443" },
        { label: "Shayestaganj", value: "555" },
    ],
    "36": [
        { label: "Bakshiganj", value: "260" },
        { label: "Dewanganj", value: "261" },
        { label: "Islampur", value: "262" },
        { label: "Jamalpur Sadar", value: "263" },
        { label: "Madarganj", value: "264" },
        { label: "Melandaha", value: "265" },
        { label: "Sarishabari", value: "266" },
    ],
    "23": [
        { label: "Abhay Nagar", value: "155" },
        { label: "Bagherpara", value: "156" },
        { label: "Chowghacha", value: "157" },
        { label: "Jhikargacha", value: "158" },
        { label: "Keshabpur", value: "159" },
        { label: "Kotwali", value: "160" },
        { label: "Manirampur", value: "161" },
        { label: "Sharsha", value: "162" },
    ],
    "28": [
        { label: "Jhalakathi Sadar", value: "200" },
        { label: "Kanthalia", value: "201" },
        { label: "Nalchity", value: "202" },
        { label: "Rajapur", value: "203" },
    ],
    "20": [
        { label: "Harinakunda", value: "142" },
        { label: "Jhenaidaha Sadar", value: "143" },
        { label: "Kaliganj", value: "144" },
        { label: "Kotchandpur", value: "145" },
        { label: "Mahespur", value: "146" },
        { label: "Shailkupa", value: "147" },
    ],
    "9": [
        { label: "Akkelpur", value: "60" },
        { label: "Joypurhat Sadar", value: "61" },
        { label: "Kalai", value: "62" },
        { label: "Khetlal", value: "63" },
        { label: "Panchbibi", value: "64" },
    ],
    "62": [
        { label: "Dighinala", value: "529" },
        { label: "Khagrachhari Sadar", value: "530" },
        { label: "Lakshmichhari", value: "531" },
        { label: "Mahalchhari", value: "532" },
        { label: "Manikchhari", value: "533" },
        { label: "Matiranga", value: "534" },
        { label: "Panchhari", value: "535" },
        { label: "Ramgarh", value: "536" },
    ],
    "25": [
        { label: "Batiaghata", value: "170" },
        { label: "Dacope", value: "171" },
        { label: "Daulatpur", value: "172" },
        { label: "Dighala", value: "173" },
        { label: "Dumuria", value: "174" },
        { label: "Khalishpur", value: "175" },
        { label: "Khan Jahan Ali", value: "176" },
        { label: "Khulna Sadar", value: "177" },
        { label: "Koyra", value: "178" },
        { label: "Paikgachha", value: "179" },
        { label: "Phultala", value: "180" },
        { label: "Rupsa", value: "181" },
        { label: "Sonadanga", value: "182" },
        { label: "Terokhada", value: "183" },
    ],
    "38": [
        { label: "Austagram", value: "279" },
        { label: "Bajitpur", value: "280" },
        { label: "Bhairab", value: "281" },
        { label: "Hossenpur", value: "282" },
        { label: "Itna", value: "283" },
        { label: "Karimganj", value: "284" },
        { label: "Katiadi", value: "285" },
        { label: "Kishoreganj Sadar", value: "286" },
        { label: "Kuliar Char", value: "287" },
        { label: "Mithamoin", value: "288" },
        { label: "Nikli", value: "289" },
        { label: "Pakundia", value: "290" },
        { label: "Tarail", value: "291" },
    ],
    "7": [
        { label: "Bhurungamari", value: "43" },
        { label: "Char Rajibpur", value: "44" },
        { label: "Chilmari", value: "45" },
        { label: "Kurigram Sadar", value: "46" },
        { label: "Nageshwari", value: "47" },
        { label: "Phulbari", value: "48" },
        { label: "Rajarhat", value: "49" },
        { label: "Rajibpur", value: "50" },
        { label: "Rowmari", value: "51" },
        { label: "Ulipur", value: "52" },
    ],
    "17": [
        { label: "Bheramara", value: "129" },
        { label: "Daulatpur", value: "130" },
        { label: "Khoksa", value: "131" },
        { label: "Kumarkhali", value: "132" },
        { label: "Kushtia Sadar", value: "133" },
        { label: "Mirpur", value: "134" },
    ],
    "57": [
        { label: "Komol Nogor", value: "476" },
        { label: "Lakshmipur Sadar", value: "477" },
        { label: "Raipur", value: "478" },
        { label: "Ramganj", value: "479" },
        { label: "Ramgati", value: "480" },
    ],
    "5": [
        { label: "Aditmari", value: "30" },
        { label: "Hatibanda", value: "31" },
        { label: "Kaliganj", value: "32" },
        { label: "Lalmonirhat Sadar", value: "33" },
        { label: "Patgram", value: "34" },
    ],
    "48": [
        { label: "Kalkini", value: "396" },
        { label: "Madaripur Sadar", value: "397" },
        { label: "Rajoir", value: "398" },
        { label: "Shibchar", value: "399" },
    ],
    "21": [
        { label: "Magura Sadar", value: "148" },
        { label: "Mohammadpur", value: "149" },
        { label: "Shalikha", value: "150" },
        { label: "Sreepur", value: "151" },
    ],
    "39": [
        { label: "Daulatpur", value: "292" },
        { label: "Ghior", value: "293" },
        { label: "Harirampur", value: "294" },
        { label: "Manikganj Sadar", value: "295" },
        { label: "Saturia", value: "296" },
        { label: "Shibalaya", value: "297" },
        { label: "Singair", value: "298" },
    ],
    "18": [
        { label: "Gangni", value: "135" },
        { label: "Meherpur Sadar", value: "136" },
        { label: "Mujib Nagar", value: "137" },
    ],
    "52": [
        { label: "Baralekha", value: "429" },
        { label: "Juri", value: "430" },
        { label: "Kamalganj", value: "431" },
        { label: "Kulaura", value: "432" },
        { label: "Moulvibazar Sadar", value: "433" },
        { label: "Rajnagar", value: "434" },
        { label: "Sreemangal", value: "435" },
    ],
    "44": [
        { label: "Gazaria", value: "371" },
        { label: "Louhajang", value: "372" },
        { label: "Munshiganj Sadar", value: "373" },
        { label: "Serajdikhan", value: "374" },
        { label: "Sreenagar", value: "375" },
        { label: "Tongibari", value: "376" },
    ],
    "34": [
        { label: "Bhalukha", value: "243" },
        { label: "Dhobaura", value: "244" },
        { label: "Fulbaria", value: "245" },
        { label: "Gaffargaon", value: "246" },
        { label: "Gauripur", value: "247" },
        { label: "Haluaghat", value: "248" },
        { label: "Ishwarganj", value: "249" },
        { label: "Muktagachha", value: "250" },
        { label: "Mymensingh Sadar", value: "251" },
        { label: "Nandail", value: "252" },
        { label: "Phulpur", value: "253" },
        { label: "Tarakanda", value: "554" },
        { label: "Trishal", value: "254" },
    ],
    "11": [
        { label: "Atrai", value: "77" },
        { label: "Badalgachhi", value: "78" },
        { label: "Dhamoirhat", value: "79" },
        { label: "Mahadebpur", value: "80" },
        { label: "Manda", value: "81" },
        { label: "Naogaon Sadar", value: "82" },
        { label: "Niamatpur", value: "83" },
        { label: "Patnitala", value: "84" },
        { label: "Porsha", value: "85" },
        { label: "Raninagar", value: "86" },
        { label: "Sapahar", value: "87" },
    ],
    "22": [
        { label: "Kalia", value: "152" },
        { label: "Lohagara", value: "153" },
        { label: "NarailSadar", value: "154" },
    ],
    "43": [
        { label: "Araihazar", value: "366" },
        { label: "Bandar", value: "367" },
        { label: "Narayanganj Sadar", value: "368" },
        { label: "Rupganj", value: "369" },
        { label: "Siddirganj", value: "559" },
        { label: "Sonargaon", value: "370" },
    ],
    "42": [
        { label: "Belabo", value: "360" },
        { label: "Manohardi", value: "361" },
        { label: "Narsingdi Sadar", value: "362" },
        { label: "Palash", value: "363" },
        { label: "Roypura", value: "364" },
        { label: "Shibpur", value: "365" },
    ],
    "12": [
        { label: "Bagati Para", value: "88" },
        { label: "Baraigram", value: "89" },
        { label: "Gurudaspur", value: "90" },
        { label: "Lalpur", value: "91" },
        { label: "Naldanga", value: "556" },
        { label: "Natore Sadar", value: "92" },
        { label: "Singra", value: "93" },
    ],
    "33": [
        { label: "Atpara", value: "233" },
        { label: "Barhatta", value: "234" },
        { label: "Durgapur", value: "235" },
        { label: "Kalmakanda", value: "236" },
        { label: "Kendua", value: "237" },
        { label: "Khaliajuri", value: "238" },
        { label: "Madan", value: "239" },
        { label: "Mohanganj", value: "240" },
        { label: "Netrokona Sadar", value: "241" },
        { label: "Purbadhala", value: "242" },
    ],
    "4": [
        { label: "Dimla", value: "24" },
        { label: "Domar", value: "25" },
        { label: "Jaldhaka", value: "26" },
        { label: "Kishoreganj", value: "27" },
        { label: "Nilphamari Sadar", value: "28" },
        { label: "Saidpur", value: "29" },
    ],
    "58": [
        { label: "Begumganj", value: "481" },
        { label: "Chatkhil", value: "482" },
        { label: "Companiganj", value: "483" },
        { label: "Hatiya", value: "484" },
        { label: "Kobirhat", value: "485" },
        { label: "Noakhali Sadar (Sudharam)", value: "486" },
        { label: "Senbagh", value: "487" },
        { label: "Sonaimuri", value: "488" },
        { label: "Subornachhar", value: "489" },
    ],
    "16": [
        { label: "Atgharia", value: "120" },
        { label: "Bera", value: "121" },
        { label: "Bhangura", value: "122" },
        { label: "Chatmohar", value: "123" },
        { label: "Faridpur", value: "124" },
        { label: "Ishwardi", value: "125" },
        { label: "Pabna Sadar", value: "126" },
        { label: "Santhia", value: "127" },
        { label: "Sujanagar", value: "128" },
    ],
    "1": [
        { label: "Atwari", value: "1" },
        { label: "Boda", value: "2" },
        { label: "Debiganj", value: "3" },
        { label: "Panchagarh Sadar", value: "4" },
        { label: "Tentulia", value: "5" },
    ],
    "31": [
        { label: "Bauphal", value: "221" },
        { label: "Dashmina", value: "222" },
        { label: "Dumki", value: "223" },
        { label: "Galachipa", value: "224" },
        { label: "Kala Para", value: "225" },
        { label: "Mirzaganj", value: "226" },
        { label: "Patuakhali Sadar", value: "227" },
        { label: "Rangabali", value: "557" },
    ],
    "27": [
        { label: "Bhandaria", value: "193" },
        { label: "Indurkani", value: "199" },
        { label: "Kawkhali", value: "194" },
        { label: "Mathbaria", value: "195" },
        { label: "Nazirpur", value: "196" },
        { label: "Nesarabad (Swarupkati)", value: "197" },
        { label: "Pirojpur Sadar", value: "198" },
    ],
    "46": [
        { label: "Baliakandi", value: "386" },
        { label: "Goalanda", value: "387" },
        { label: "Kalukhali", value: "388" },
        { label: "Pangsha", value: "389" },
        { label: "Rajbari Sadar", value: "390" },
    ],
    "14": [
        { label: "Bagha", value: "99" },
        { label: "Baghmara", value: "100" },
        { label: "Boalia (Sadar)", value: "101" },
        { label: "Charghat", value: "102" },
        { label: "Durgapur", value: "103" },
        { label: "Godagari", value: "104" },
        { label: "Matihar", value: "105" },
        { label: "Mohanpur", value: "106" },
        { label: "Paba", value: "107" },
        { label: "Puthia", value: "108" },
        { label: "Rajpara", value: "109" },
        { label: "Tanore", value: "110" },
    ],
    "63": [
        { label: "Bagaichhari", value: "537" },
        { label: "Barkal", value: "538" },
        { label: "Belaichhari", value: "539" },
        { label: "Juraichhari", value: "540" },
        { label: "Kaptai", value: "541" },
        { label: "Kawkhali (Betbunia)", value: "542" },
        { label: "Langadu", value: "543" },
        { label: "Naniarchar", value: "544" },
        { label: "Rajasthali", value: "545" },
        { label: "Rangamati Sadar", value: "546" },
    ],
    "6": [
        { label: "Badarganj", value: "35" },
        { label: "Gangachara", value: "36" },
        { label: "Kaunia", value: "37" },
        { label: "Mitha Pukur", value: "38" },
        { label: "Pirgachha", value: "39" },
        { label: "Pirganj", value: "40" },
        { label: "Rangpur Sadar", value: "41" },
        { label: "Taraganj", value: "42" },
    ],
    "24": [
        { label: "Assasuni", value: "163" },
        { label: "Debhata", value: "164" },
        { label: "Kalaroa", value: "165" },
        { label: "Kaliganj", value: "166" },
        { label: "Satkhira Sadar", value: "167" },
        { label: "Shyamnagar", value: "168" },
        { label: "Tala", value: "169" },
    ],
    "49": [
        { label: "Bhaderganj", value: "400" },
        { label: "Damudya", value: "401" },
        { label: "Gosairhat", value: "402" },
        { label: "Naria", value: "403" },
        { label: "Palong(Sadar)", value: "404" },
        { label: "Zanjira", value: "405" },
    ],
    "35": [
        { label: "Jhenaigati", value: "255" },
        { label: "Nakla", value: "256" },
        { label: "Nalitabari", value: "257" },
        { label: "Sherpur Sadar", value: "258" },
        { label: "Sreebardi", value: "259" },
    ],
    "15": [
        { label: "Belkuchi", value: "111" },
        { label: "Chauhali", value: "112" },
        { label: "Kamarkhanda", value: "113" },
        { label: "Kazipur", value: "114" },
        { label: "Royganj", value: "115" },
        { label: "Shahjadpur", value: "116" },
        { label: "Sirajganj Sadar", value: "117" },
        { label: "Tarash", value: "118" },
        { label: "Ullah Para", value: "119" },
    ],
    "50": [
        { label: "Bishwambarpur", value: "406" },
        { label: "Chhatak", value: "407" },
        { label: "Derai", value: "409" },
        { label: "Dharmapasha", value: "410" },
        { label: "Dowarabazar", value: "411" },
        { label: "Jagannatpur", value: "412" },
        { label: "Jamalganj", value: "413" },
        { label: "Madhyanagar", value: "569" },
        { label: "Shalla", value: "414" },
        { label: "Shantiganj/ Dakshin Sunamganj", value: "408" },
        { label: "Sunamganj Sadar", value: "415" },
        { label: "Tahirpur", value: "416" },
    ],
    "51": [
        { label: "Balaganj", value: "417" },
        { label: "Beanibazar", value: "418" },
        { label: "Bishwanath", value: "419" },
        { label: "Companiganj", value: "420" },
        { label: "Dakshin Surma", value: "427" },
        { label: "Fenchuganj", value: "421" },
        { label: "Golapganj", value: "422" },
        { label: "Gowainghat", value: "423" },
        { label: "Jaintapur", value: "424" },
        { label: "Kanaighat", value: "425" },
        { label: "Osmaninagar", value: "568" },
        { label: "Sylhet Sadar", value: "426" },
        { label: "Zakiganj", value: "428" },
    ],
    "37": [
        { label: "Basail", value: "267" },
        { label: "Bhuapur", value: "268" },
        { label: "Delduar", value: "269" },
        { label: "Dhonbari", value: "270" },
        { label: "Ghatail", value: "271" },
        { label: "Gopalpur", value: "272" },
        { label: "Kalihati", value: "273" },
        { label: "Madhupur", value: "274" },
        { label: "Mirzapur", value: "275" },
        { label: "Nagarpur", value: "276" },
        { label: "Sakhipur", value: "277" },
        { label: "Tangail Sadar", value: "278" },
    ],
    "2": [
        { label: "Baliadangi", value: "6" },
        { label: "Haripur", value: "7" },
        { label: "Pirganj", value: "8" },
        { label: "Ranisankail", value: "9" },
        { label: "Thakurgaon Sadar", value: "10" },
    ],
};
